In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [4]:
try :
    df = pd.read_csv ("dataset/sales1.csv")
    print ("Data berhasil masuk")
except FileNotFoundError :
    print ("Data tidak masuk")

Data berhasil masuk

ini cuma debugging ngeliat datanya masuk atau engga

In [ ]:
df['date'] = pd.to_datetime(df['date'], dayfirst=True)
print(df.dtypes)

order_id             int64
date        datetime64[ns]
store               object
product             object
quantity             int64
sales              float64
dtype: object

jadi untuk ngubuah date jadi date time itu pakai pd.to datetime, dan pakai dayfirst=True karena kita hari duluan, bukan Month duluan.

Group data berdasarkan date (pakai groupby),Karena ada kolom sales dan quantity kita pakai sum().

In [ ]:
#Ini contoh kita pakai group by untuk Total sales per tanggal
grouped_date1 = df.groupby('date')['sales'].sum()
print(grouped_date1)

date
2023-01-01    2508.20
2023-01-02    2403.35
2023-01-03    2565.00
2023-01-04    2220.10
2023-01-05    2418.85
               ...
2023-06-26    5875.90
2023-06-27    5975.65
2023-06-28    4728.90
2023-06-29    4450.75
2023-06-30    5481.32
Name: sales, Length: 181, dtype: float64

In [ ]:
#Ini contoh kita pakai group by untuk Total quantity & sales per tanggal
grouped_date2 = df.groupby('date')[['quantity', 'sales']].sum()
print(grouped_date2)

            quantity    sales
date
2023-01-01       802  2508.20
2023-01-02       790  2403.35
2023-01-03       823  2565.00
2023-01-04       726  2220.10
2023-01-05       778  2418.85
...              ...      ...
2023-06-26      1837  5875.90
2023-06-27      1962  5975.65
2023-06-28      1531  4728.90
2023-06-29      1429  4450.75
2023-06-30      1590  5481.32

[181 rows x 2 columns]

In [26]:

#group data berdasarkan date nih
grouped_date = df.groupby(['date', 'store', 'product']) [['quantity', 'sales']].sum()
#kita simpan ke data frame
grouped_date = grouped_date.reset_index()
grouped_date.head(10)

        date    store                product  quantity   sales
0 2023-01-01  Astoria       Barista Espresso        29  112.50
1 2023-01-01  Astoria               Biscotti         5   16.75
2 2023-01-01  Astoria       Brewed Black tea        13   37.00
3 2023-01-01  Astoria        Brewed Chai tea        42  127.60
4 2023-01-01  Astoria       Brewed Green tea        15   40.50
5 2023-01-01  Astoria      Brewed herbal tea        29   78.00
6 2023-01-01  Astoria            Drip coffee        17   42.50
7 2023-01-01  Astoria  Gourmet brewed coffee        35   90.80
8 2023-01-01  Astoria          Hot chocolate        36  142.50
9 2023-01-01  Astoria  Organic brewed coffee        17   51.00

Pada tahap ini, data penjualan dikelompokkan berdasarkan tanggal (date) untuk memperoleh total jumlah produk (quantity) dan total penjualan (sales) per hari.

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   order_id  149116 non-null  int64
 1   date      149116 non-null  datetime64[ns]
 2   store     149116 non-null  object
 3   product   149116 non-null  object
 4   quantity  149116 non-null  int64
 5   sales     149116 non-null  float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 6.8+ MB

In [16]:
df.describe()

,order_id,date,quantity,sales
count,149116.000000,149116,149116.000000,149116.000000
mean,74737.371872,2023-04-15 11:50:32.173609984,1.438276,4.686367
min,1.000000,2023-01-01 00:00:00,1.000000,0.800000
25%,37335.750000,2023-03-06 00:00:00,1.000000,3.000000
50%,74727.500000,2023-04-24 00:00:00,1.000000,3.750000
75%,112094.250000,2023-05-30 00:00:00,2.000000,6.000000
max,149456.000000,2023-06-30 00:00:00,8.000000,360.000000
std,43153.600016,NaN,0.542509,4.227099